Check if all options are set before setup and download actions

diff --git a/precc b/precc
--- a/precc
+++ b/precc
@@ -69,13 +69,22 @@ $APP [options] (setup|download|extract_monolingual|dedupe)...
 -l, --languagesfile    file which specifies which languages to run the deduper on
 -c, --config           custom configeration file
 -j, --jobs             number of simultaneous jobs to run for GNU parallel
+--progress             if selected GNU parallel will display progress
 --sshloginfile         ssh file for GNU parallel
 EOF
 }
 
+check_setup_opts() {
+    if [[ -z "${WET_DIR}" ]] || [[ -z "${MONOLINGUAL_DIR}" ]] || [[ -z "${DEDUPED_DIR}" ]] || [[ -z "${CRAWL_URL}" ]]; then
+        echo "For the setup action --wet-dir, --monolingual-dir, --deduped-dir and --crawl-url must be set." >&2
+        exit 1
+    fi
+}
+
 setup() {
+    check_setup_opts
+
     # Make directories for specified crawl.
-    # TODO: Check wether directory names are provided.
     mkdir -p "${WET_DIR}"
     mkdir -p "${MONOLINGUAL_DIR}"
     mkdir -p "${DEDUPED_DIR}"
@@ -99,24 +108,16 @@ setup() {
     done
 }
 
-count_downloads() {
-    TOTAL=0
-    DOWNLOADED=0
-    for path in $(cat "${WET_DIR}/wet.paths.http"); do
-        TOTAL=$((TOTAL+1))
-        # TODO: Explain awk expression.
-        FILENAME=$(echo $path | awk 'BEGIN { FS = "/" } { print $(NF-2) "/" $(NF)}')
-        if [ -f ${FILENAME}.done ]; then
-            DOWNLOADED=$((DOWNLOADED+1))
-        fi
-    done
-    DIFFERENCE=$((TOTAL-DOWNLOADED))
-    if [[ "$DIFFERENCE" -ne 0 ]]; then
-        echo "There are ${DIFFERENCE} files missing/incomplete"
+check_download_opts() {
+    if [[ -z "${WET_DIR}" ]]; then
+        echo "For the download action --wet-dir must be set." >&2
+        exit 1
     fi
 }
 
 download() {
+    check_download_opts
+
     cd "${WET_DIR}"
     PARALLEL_OPTIONS="${PARALLEL_OPTIONS} --wd ${WET_DIR}"
 
@@ -132,6 +133,23 @@ download() {
         echo "Counting downloaded files.."
     done
     echo "All files downloaded"
+}
+
+count_downloads() {
+    TOTAL=0
+    DOWNLOADED=0
+    for path in $(cat "${WET_DIR}/wet.paths.http"); do
+        TOTAL=$((TOTAL+1))
+        # TODO: Explain awk expression.
+        FILENAME=$(echo $path | awk 'BEGIN { FS = "/" } { print $(NF-2) "/" $(NF)}')
+        if [ -f ${FILENAME}.done ]; then
+            DOWNLOADED=$((DOWNLOADED+1))
+        fi
+    done
+    DIFFERENCE=$((TOTAL-DOWNLOADED))
+    if [[ "$DIFFERENCE" -ne 0 ]]; then
+        echo "There are ${DIFFERENCE} files missing/incomplete"
+    fi
 }
 
 check_monolingual_opts() {
